SET search_path TO app_jobwiseai;

INSERT INTO app_jobwiseai.tools (
  id, name, logo_url, one_liner, description, overview, website_url,
  categories, role, pricing_model, integration_difficulty,
  rating, reviews_count, verified, status, editor_pick,
  key_features, pros, cons, ideal_use_case, implementation_steps, roi
) VALUES
(
  'a1b2c3d4-0001-0001-0001-000000000001',
  'OutreachAI',
  'https://ui-avatars.com/api/?name=OutreachAI&background=3b82f6&color=fff&bold=true',
  'AI-powered sales email sequences that book more meetings.',
  'OutreachAI automates personalized cold email campaigns using AI to write, schedule, and optimize every message for your prospects.',
  'OutreachAI is the leading AI-powered sales engagement platform. Using advanced NLP and behavioral data, it crafts hyper-personalized email sequences that adapt based on prospect interactions — dramatically increasing reply rates and booked meetings.',
  'https://outreachai.example.com',
  ARRAY['Email Automation','Lead Generation','CRM Integration'],
  'sales',
  'Paid',
  3,
  4.8, 1240, true, 'active', true,
  '[{"title":"AI Sequence Builder","description":"Generate full multi-touch email sequences from a single prompt."},{"title":"Smart Send Time","description":"Sends at the exact time each prospect is most likely to open."},{"title":"CRM Sync","description":"Bi-directional sync with Salesforce, HubSpot, and Pipedrive."}]',
  to_jsonb(ARRAY['Dramatically reduces prospecting time','High deliverability rates','Easy CRM integration']),
  to_jsonb(ARRAY['Premium pricing','Learning curve for advanced sequences']),
  'B2B SDRs and Account Executives managing 100+ prospects per week.',
  '[{"step":1,"title":"Connect CRM","description":"Authorize OutreachAI to sync your contact data from Salesforce or HubSpot."},{"step":2,"title":"Define ICP","description":"Set your Ideal Customer Profile using firmographic and technographic filters."},{"step":3,"title":"Generate Sequence","description":"Use the AI Sequence Builder to create a 5-touch email campaign in under 5 minutes."},{"step":4,"title":"Launch & Monitor","description":"Activate the campaign and monitor open/reply rates in the live dashboard."}]',
  '{"metric":"15 hours/week saved","description":"Reduced manual prospecting from 20 hours to 5 hours per week across the entire SDR team.","author":"Sarah Jenkins","role":"VP of Sales, TechFlow"}'
),
(
  'a1b2c3d4-0002-0002-0002-000000000002',
  'CodeFlow',
  'https://ui-avatars.com/api/?name=CodeFlow&background=8b5cf6&color=fff&bold=true',
  'Context-aware AI code completion for every major IDE.',
  'CodeFlow provides intelligent, repository-aware code completions that understand your entire codebase — not just the current file.',
  'CodeFlow goes beyond simple autocomplete. Its context engine indexes your entire repository to provide suggestions that are aware of your architecture, naming conventions, and existing functions — dramatically reducing time spent writing boilerplate.',
  'https://codeflow.example.com',
  ARRAY['Code Completion','Developer Tools','IDE Integration'],
  'engineering',
  'Freemium',
  2,
  4.9, 850, true, 'active', true,
  '[{"title":"Repo-Wide Context","description":"Understands your full codebase, not just the open file."},{"title":"Multi-Language Support","description":"Works with 30+ programming languages."},{"title":"Test Generation","description":"Auto-generates unit tests for any function with a single shortcut."}]',
  to_jsonb(ARRAY['Extremely accurate suggestions','Massive time savings on boilerplate','Strong privacy mode']),
  to_jsonb(ARRAY['Resource-intensive on large repos','Free tier limited to 3 files']),
  'Engineering teams building complex, multi-file applications in any language.',
  '[{"step":1,"title":"Install Extension","description":"Install the CodeFlow extension from your IDE marketplace (VS Code, JetBrains, Neovim)."},{"step":2,"title":"Authenticate","description":"Sign in with GitHub or Google to activate your license."},{"step":3,"title":"Index Repository","description":"Run codeflow index in your terminal to build the context model for your repo."},{"step":4,"title":"Start Coding","description":"Accept suggestions with Tab or cycle through alternatives with Alt+]."}]',
  '{"metric":"10 hours/week saved","description":"Engineers report spending 10+ fewer hours per week on repetitive code, allowing them to focus on architecture.","author":"Michael Chen","role":"Senior DevOps, CloudScale"}'
),
(
  'a1b2c3d4-0003-0003-0003-000000000003',
  'TalentScout',
  'https://ui-avatars.com/api/?name=TalentScout&background=10b981&color=fff&bold=true',
  'Screen hundreds of resumes in minutes with AI-powered HR tools.',
  'TalentScout uses AI to score, rank, and summarize resumes so your HR team focuses only on the best candidates.',
  'TalentScout transforms the resume screening process. Upload a job description and hundreds of resumes — TalentScout scores each candidate against your requirements, flags red-flags, highlights top candidates, and drafts interview questions automatically.',
  'https://talentscout.example.com',
  ARRAY['Resume Screening','Candidate Ranking','HR Automation'],
  'hr',
  'Trial',
  5,
  4.6, 320, true, 'active', false,
  '[{"title":"AI Resume Scoring","description":"Scores candidates 0-100 against your exact job description criteria."},{"title":"Bias Detection","description":"Flags potentially biased language in job postings and screens for fair evaluation."},{"title":"Interview Question Generator","description":"Generates role-specific interview questions for each shortlisted candidate."}]',
  to_jsonb(ARRAY['Drastically reduces screening time','Bias detection is a standout feature','Clean candidate comparison view']),
  to_jsonb(ARRAY['Requires clean resume formatting','Integration with some ATS systems is manual']),
  'HR teams and recruiters handling high-volume hiring for technical and non-technical roles.',
  '[{"step":1,"title":"Upload Job Description","description":"Paste or upload your JD to set the scoring rubric."},{"step":2,"title":"Batch Upload Resumes","description":"Upload resumes in bulk (PDF, DOCX) or connect your ATS integration."},{"step":3,"title":"Review Rankings","description":"Review the AI-generated scorecard and candidate summary for each applicant."},{"step":4,"title":"Export Shortlist","description":"Export top candidates to your ATS or share the shortlist with hiring managers."}]',
  '{"metric":"8 hours/hire saved","description":"Reduced average time-to-shortlist from 3 days to 4 hours.","author":"Priya Sharma","role":"Head of Talent, GrowthCo"}'
),
(
  'a1b2c3d4-0004-0004-0004-000000000004',
  'MarketMind',
  'https://ui-avatars.com/api/?name=MarketMind&background=f59e0b&color=fff&bold=true',
  'From keyword to published blog post in one click.',
  'MarketMind generates SEO-optimized blog content, social copy, and ad creative — all from a single keyword or brief.',
  'MarketMind is the content marketing team''s secret weapon. Input a keyword, target audience, and tone — MarketMind produces a full, SEO-structured blog post with meta description, header tags, and internal link suggestions. Includes a brand voice training tool.',
  'https://marketmind.example.com',
  ARRAY['Content Generation','SEO','Social Media'],
  'marketing',
  'Paid',
  1,
  4.7, 2100, true, 'active', true,
  '[{"title":"Brand Voice Training","description":"Train MarketMind on your existing content to match your unique tone."},{"title":"SEO Brief Analyzer","description":"Ingests top-ranking competitor articles and builds a content brief to outrank them."},{"title":"Content Calendar","description":"AI-suggested publishing schedule based on your keyword strategy."}]',
  to_jsonb(ARRAY['Extremely fast content production','Strong SEO optimization built-in','Multi-format output (blog, social, email)']),
  to_jsonb(ARRAY['Requires human editing for technical topics','Brand voice training takes initial setup time']),
  'Content marketers and SEO teams producing high-volume content across multiple channels.',
  '[{"step":1,"title":"Set Brand Voice","description":"Upload 5-10 pieces of your existing content to train MarketMind on your brand tone."},{"step":2,"title":"Research Keywords","description":"Enter target keywords; MarketMind analyzes SERPs and suggests a content angle."},{"step":3,"title":"Generate Draft","description":"Generate a full draft with one click. Review the AI outline first for best results."},{"step":4,"title":"Publish","description":"Export to WordPress, Webflow, or your CMS via native integrations."}]',
  '{"metric":"20 articles/month increase","description":"Increased content output from 5 to 25 articles per month with the same 2-person team.","author":"Lisa Park","role":"Content Director, ScaleUp Inc."}'
),
(
  'a1b2c3d4-0005-0005-0005-000000000005',
  'ForecastPro',
  'https://ui-avatars.com/api/?name=ForecastPro&background=6366f1&color=fff&bold=true',
  'AI-powered financial modeling and forecasting for modern finance teams.',
  'ForecastPro connects to your financial data and generates dynamic models, variance analysis, and forecasts automatically.',
  'ForecastPro replaces hours of manual spreadsheet work with AI-driven financial models. Connect your accounting system, ERP, or raw CSVs and get instant P&L projections, cash flow forecasts, and scenario analysis — all in a collaborative workspace.',
  'https://forecastpro.example.com',
  ARRAY['Financial Modeling','Forecasting','FP&A'],
  'finance',
  'Contact',
  7,
  4.5, 150, true, 'active', false,
  '[{"title":"Scenario Modeling","description":"Build best/base/worst case scenarios with a single slider."},{"title":"Variance Analysis","description":"Automatically flags budget vs actual variances with root-cause summaries."},{"title":"ERP Integration","description":"Native connectors for QuickBooks, Netsuite, Xero, and SAP."}]',
  to_jsonb(ARRAY['Eliminates manual model building','Excellent scenario analysis tools','Strong audit trail']),
  to_jsonb(ARRAY['High price point for SMBs','Steep learning curve for non-finance users','Contact-only pricing lacks transparency']),
  'FP&A teams and CFOs at Series B+ companies managing complex multi-entity finances.',
  '[{"step":1,"title":"Connect Data Source","description":"Authorize ForecastPro to read from your accounting system or upload a chart of accounts CSV."},{"step":2,"title":"Map Accounts","description":"Use the AI-assisted account mapping wizard to classify your P&L and Balance Sheet line items."},{"step":3,"title":"Build Base Model","description":"ForecastPro auto-generates a 12-month rolling forecast from historical data."},{"step":4,"title":"Run Scenarios","description":"Use the Scenario Builder to stress-test the model against different growth assumptions."}]',
  '{"metric":"40 hours/month saved","description":"Eliminated manual monthly close model rebuild, freeing the FP&A team for strategic analysis.","author":"David Kim","role":"CFO, NovaCorp"}'
),
(
  'a1b2c3d4-0006-0006-0006-000000000006',
  'UserVoice AI',
  'https://ui-avatars.com/api/?name=UserVoice&background=ec4899&color=fff&bold=true',
  'Turn thousands of user feedback signals into product decisions in minutes.',
  'UserVoice AI aggregates feedback from all channels and uses NLP to surface the themes, sentiment, and feature requests driving your roadmap.',
  'UserVoice AI connects to your support tickets, app reviews, NPS surveys, and sales call transcripts. Its AI clusters feedback by theme, assigns sentiment scores, and links each insight directly to your product roadmap — so you always know what to build next.',
  'https://uservoice.example.com',
  ARRAY['User Feedback','Product Analytics','NLP'],
  'product',
  'Freemium',
  4,
  4.8, 430, true, 'active', false,
  '[{"title":"Omnichannel Ingestion","description":"Connects to Intercom, Zendesk, App Store, G2, Slack, and sales call tools."},{"title":"Theme Clustering","description":"AI automatically groups feedback into themes and sub-themes."},{"title":"Roadmap Integration","description":"Push insights directly to Linear, Jira, or Productboard."}]',
  to_jsonb(ARRAY['Saves enormous time on feedback synthesis','Excellent integrations ecosystem','Clear visual theme explorer']),
  to_jsonb(ARRAY['AI theme naming can be vague','Free tier limited to 3 data sources']),
  'Product Managers and UX Researchers managing feedback at scale across multiple channels.',
  '[{"step":1,"title":"Connect Sources","description":"Authorize at least 2 feedback sources (e.g., Zendesk + App Store reviews)."},{"step":2,"title":"Run First Analysis","description":"Click Analyze to let UserVoice AI process and cluster your first 1,000 feedback items."},{"step":3,"title":"Review Themes","description":"Explore the Theme Explorer to validate and rename AI-generated clusters."},{"step":4,"title":"Export to Roadmap","description":"Push top themes directly to your roadmap tool as Epics or Feature requests."}]',
  '{"metric":"12 hours/sprint saved","description":"Eliminated the manual feedback synthesis session before each sprint planning.","author":"Amy Tran","role":"Head of Product, AppCo"}'
),
(
  'a1b2c3d4-0007-0007-0007-000000000007',
  'LinkedFlow AI',
  'https://ui-avatars.com/api/?name=LinkedFlow&background=0077b5&color=fff&bold=true',
  'Automate LinkedIn outreach without losing the personal touch.',
  'LinkedFlow AI writes personalized LinkedIn connection messages and follow-ups based on each prospect''s profile, posts, and company news.',
  'LinkedFlow AI integrates with LinkedIn Sales Navigator to identify, score, and engage prospects at scale. Every message is written by AI to reference specific details from the prospect''s profile — making automation feel genuinely personal.',
  'https://linkedflow.example.com',
  ARRAY['LinkedIn Automation','Social Selling','Lead Generation'],
  'sales',
  'Paid',
  3,
  4.8, 2100, true, 'active', true,
  '[{"title":"Profile-Aware Messaging","description":"References prospect''s recent posts, career history, and company news in every message."},{"title":"Campaign Analytics","description":"Full funnel view: connection rate, reply rate, meeting booked rate."},{"title":"A/B Testing","description":"Test 3 message variants simultaneously to optimize performance."}]',
  to_jsonb(ARRAY['Messages feel genuinely personal','Strong analytics dashboard','Easy LinkedIn Sales Navigator integration']),
  to_jsonb(ARRAY['LinkedIn API rate limits can slow campaigns','Requires Sales Navigator subscription']),
  'B2B sales teams using LinkedIn as their primary prospecting channel.',
  '[{"step":1,"title":"Connect LinkedIn","description":"Authorize LinkedFlow with your LinkedIn Sales Navigator account."},{"step":2,"title":"Build Prospect List","description":"Use Sales Navigator filters to create a target list of 100-500 prospects."},{"step":3,"title":"Create Campaign","description":"Define your outreach sequence (connection request + 3 follow-ups). LinkedFlow AI writes each message."},{"step":4,"title":"Launch & Optimize","description":"Launch the campaign and use A/B test results to improve message performance weekly."}]',
  '{"metric":"3x more booked meetings","description":"Tripled the number of monthly meetings booked from LinkedIn without increasing headcount.","author":"James Reed","role":"Sales Manager, B2BGrow"}'
),
(
  'a1b2c3d4-0008-0008-0008-000000000008',
  'ReachOut GPT',
  'https://ui-avatars.com/api/?name=ReachOut&background=14b8a6&color=fff&bold=true',
  'Hyper-personalized cold email icebreakers at scale.',
  'ReachOut GPT generates unique opening lines for every cold email by researching each prospect online — in seconds.',
  'ReachOut GPT eliminates the most time-consuming part of cold email: the personalized first line. Enter a prospect''s LinkedIn URL or email, and the AI researches their recent activity, company news, and professional background to craft a unique, relevant opening line.',
  'https://reachoutgpt.example.com',
  ARRAY['Cold Email','Personalization','Email Automation'],
  'marketing',
  'Freemium',
  2,
  4.2, 850, false, 'active', false,
  '[{"title":"One-Click Research","description":"Scrapes LinkedIn, company website, and news to build a prospect dossier in seconds."},{"title":"Bulk Processing","description":"Process a CSV of 500 prospects in under 10 minutes."},{"title":"CRM Push","description":"Push personalized icebreakers directly into Outreach, Salesloft, or HubSpot fields."}]',
  to_jsonb(ARRAY['Massive time saver for personalization','Output quality is consistently high','Bulk processing is fast']),
  to_jsonb(ARRAY['Free tier limited to 20 icebreakers/month','Occasional hallucinations on less-known prospects']),
  'Marketing and sales teams running high-volume cold email campaigns.',
  '[{"step":1,"title":"Upload Prospect List","description":"Upload a CSV with LinkedIn URLs or email addresses."},{"step":2,"title":"Select Research Depth","description":"Choose Quick (LinkedIn only) or Deep (LinkedIn + company news + web)."},{"step":3,"title":"Review & Edit","description":"Review the generated icebreakers and edit any that need refinement."},{"step":4,"title":"Export","description":"Export the enriched CSV or push directly to your email sequencer."}]',
  '{"metric":"45% higher reply rate","description":"Personalized icebreakers increased cold email reply rates from 4% to 5.8%.","author":"Nina Walsh","role":"Growth Lead, SeedRocket"}'
),
(
  'a1b2c3d4-0009-0009-0009-000000000009',
  'SignalScout',
  'https://ui-avatars.com/api/?name=SignalScout&background=f97316&color=fff&bold=true',
  'Find verified contact data and buying signals for any B2B prospect.',
  'SignalScout combines contact data enrichment with real-time buying signal detection — so you always know who to call and exactly when to call them.',
  'SignalScout is a B2B intelligence platform that surfaces verified email addresses, direct dials, and firmographic data for any company or contact. Its proprietary Buying Signal Engine tracks job changes, tech stack updates, and funding events to alert you when a prospect is actively in-market.',
  'https://signalscout.example.com',
  ARRAY['Contact Data','Lead Intelligence','Sales Intelligence'],
  'sales',
  'Paid',
  1,
  5.0, 310, true, 'active', true,
  '[{"title":"Buying Signal Engine","description":"Alerts you when prospects change jobs, receive funding, or add new tech to their stack."},{"title":"Data Waterfall","description":"Queries 12 data providers in sequence to maximize contact data coverage."},{"title":"Chrome Extension","description":"Reveals contact data and signals directly on LinkedIn profiles."}]',
  to_jsonb(ARRAY['Best contact data coverage in the market','Buying signals are highly actionable','Chrome extension is a standout feature']),
  to_jsonb(ARRAY['Premium pricing','Data freshness varies by geography']),
  'Sales teams that prioritize precision prospecting over high-volume cold outreach.',
  '[{"step":1,"title":"Install Chrome Extension","description":"Install the SignalScout Chrome extension and log in."},{"step":2,"title":"Set Signal Alerts","description":"Configure buying signal alerts (funding rounds, job changes, tech adds) for your target accounts."},{"step":3,"title":"Enrich Contacts","description":"Use the Chrome extension on LinkedIn or upload a CSV for bulk enrichment."},{"step":4,"title":"Act on Signals","description":"Review your Signal Feed daily and reach out to in-market prospects within 24 hours of an event."}]',
  '{"metric":"2x pipeline from same outreach volume","description":"Targeting buying signals doubled pipeline generated without increasing SDR headcount.","author":"Carlos Rivera","role":"Director of Sales, PipelineMax"}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO app_jobwiseai.stat_metrics (label, value, change, trend) VALUES
  ('Total Tools',       '9',       '+2 this month',    'up'),
  ('Active Users',      '1,247',   '+18% vs last month','up'),
  ('Reviews Submitted', '6,020',   '+341 this week',   'up'),
  ('MRR',               '$12,480', '+$1,200 vs last',  'up')
ON CONFLICT DO NOTHING;
