import sanitizeHtml from "sanitize-html";

/**
 * Sanitize email HTML for display inside a sandboxed iframe (no scripts).
 * Allows common newsletter / calendar markup including embedded &lt;style&gt;.
 */
export function sanitizeEmailBodyHtml(html: string): string {
  return sanitizeHtml(html || '<p style="color:#64748b">Empty message.</p>', {
    allowVulnerableTags: true,
    allowedTags: sanitizeHtml.defaults.allowedTags.concat([
      "img",
      "h1",
      "h2",
      "h3",
      "h4",
      "h5",
      "h6",
      "span",
      "style",
      "table",
      "thead",
      "tbody",
      "tfoot",
      "tr",
      "th",
      "td",
      "caption",
      "colgroup",
      "col",
      "center",
      "font",
    ]),
    allowedAttributes: {
      ...sanitizeHtml.defaults.allowedAttributes,
      a: ["href", "name", "target", "rel", "style", "class", "id"],
      img: ["src", "alt", "title", "width", "height", "style", "class", "id"],
      style: ["type", "media"],
      table: [
        "class",
        "style",
        "width",
        "height",
        "align",
        "border",
        "cellpadding",
        "cellspacing",
        "bgcolor",
        "role",
        "id",
      ],
      thead: ["class", "style", "align", "bgcolor", "id"],
      tbody: ["class", "style", "align", "bgcolor", "id"],
      tfoot: ["class", "style", "align", "bgcolor", "id"],
      tr: ["class", "style", "align", "bgcolor", "height", "id"],
      th: [
        "class",
        "style",
        "colspan",
        "rowspan",
        "width",
        "height",
        "align",
        "valign",
        "bgcolor",
        "id",
      ],
      td: [
        "class",
        "style",
        "colspan",
        "rowspan",
        "width",
        "height",
        "align",
        "valign",
        "bgcolor",
        "id",
      ],
      caption: ["class", "style", "align", "id"],
      colgroup: ["class", "style", "span", "width", "id"],
      col: ["class", "style", "span", "width", "id"],
      center: ["class", "style", "id"],
      font: ["class", "style", "color", "face", "size", "id"],
      "*": [
        "class",
        "style",
        "id",
        "dir",
        "lang",
        "title",
        "role",
        "aria-label",
      ],
    },
    allowedSchemes: ["http", "https", "mailto", "data", "cid"],
    transformTags: {
      a: (tagName, attribs) => ({
        tagName,
        attribs: {
          ...attribs,
          rel: "noopener noreferrer",
          target: "_blank",
        },
      }),
    },
  });
}
